Add log_level for FPM logs
usabilla/php-docker-template pull request #169
Opened 2021-02-25 12:48 UTC by agustingomes

# Usabilla PHP Docker Template

Reviewers: @usabilla/oss-docker

## Type

Please specify the type of changes being proposed:

| Q                 | A
| ----------------- | -----
| Documentation?    | yes/no
| Dockerfile change?| yes/no
| Build feature?    | yes/no
| Apply CVE Patch?  | yes/no
| Remove CVE Patch? | yes/no

## Changelog

- Please make sure you have checked our [Contributing guidelines](https://github.com/usabilla/php-docker-template/blob/master/.github/CONTRIBUTING.md)

2021-02-25 13:27 UTC, rdohms requested changes
Missing documentation for this.

Also internally, not sure we want this, as these logs have been useful. Right @WyriHaximus ?

2021-02-25 14:24 UTC, WyriHaximus commented
> Can you please document this in the README?

@agustingomes And set the current defaults in the `Dockerfile`'s?

> Also internally, not sure we want to lower our threshold, as these logs have been useful. Right @WyriHaximus ?

@rdohms At the moment we need these logs to detect certain issues. So yes they are very useful.

2026-02-11 10:59 UTC, agustingomes commented
I will close this PR for the time being. I may reopen it at a later time.

2026-02-11 10:59 UTC, closed without merging

2026-02-11 11:02 UTC, agustingomes commented
For some reason, I could not delete the branch :( sorry about that.