[PoC] Add PHP 8.0 to the build matrix
usabilla/php-docker-template pull request #174
Opened 2021-06-15 12:13 UTC by agustingomes

# Usabilla PHP Docker Template

Reviewers: @WyriHaximus

This is a PoC PR, do not review yet.

2021-06-17 09:03 UTC, WyriHaximus requested changes
Sweet, looks like building 8.0 is new without a hitch, except for the older Alpine versions. We need to find a way to resolve that, either through more dynamic or cutting off the older Alpine versions.

2021-06-29 15:08 UTC, bendavies commented
🤞

2021-06-30 12:55 UTC, cvmiert commented
> Sweet, looks like building 8.0 is new without a hitch, except for the older Alpine versions. We need to find a way to resolve that, either through more dynamic or cutting off the older Alpine versions.

I think we can consider dropping the older Alpine versions: anything below `3.13` is [no longer supported](https://github.com/docker-library/docs/blob/master/php/README.md#supported-tags-and-respective-dockerfile-links).

2021-07-27 13:28 UTC, carusogabriel commented
Closing in favour of #179.

2021-07-27 13:28 UTC, closed without merging